name: "Run Tests"

on:
  push:
  workflow_dispatch:
    inputs:
      enableCache:
        description: "Enable cache of installed dependencies"
        type: boolean
        default: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v5
        with:
          # Enable cache, except when manually triggered and explicitly disabled.
          enable-cache: ${{ github.event_name != 'workflow_dispatch' || inputs.enableCache }}
          version: "latest"
          # As a library, we're not version-controlling uv.lock, so need pyproject.toml check.
          # See: https://github.com/astral-sh/setup-uv/issues/261#issue-2818259989
          cache-dependency-glob: |
            **/*(requirements|constraints)*.(txt|in)
            **/pyproject.toml
            **/uv.lock

      - name: Install dependencies
        run: make install-dev

      - name: Test with pytest
        run: make test

      - name: Test notebooks
        run: make test-nb
